### ISSUE TITLE
more explanation

### ISSUE THREAD

**Issue by IPECTER** [SparklyPower/SparklyPaper#13]
I wonder why we cant access biome, block, entity, etc with Parallel World Ticking in async scheduler using plugin.
I need more info.
I cant understand all.... 
and I wonder if using async getBiome/Block/Entity without TickThread check code.

sry for bad english...

**Comment by MrPowerGamerBR** [comment]
> I wonder why we cant access biome, block, entity, etc with Parallel World Ticking in async scheduler using plugin.

Because reading/editing the world in a separate thread is not thread safe, Minecraft's code wasn't meant for async access. SparklyPaper only makes world tick in parallel because worlds don't really need to access data present in other worlds to function.
