### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by rafalohaki** [SparklyPower/SparklyPaper#15]
build keeps failing

**Comment by MrPowerGamerBR** [comment]
I know, the patches need to be updated, I haven't done that yet because I do that when I update my own server (which is still running SparklyPaper 1.20.2, so I haven't tested the newer versions yet)

**Comment by ghost** [comment]
:(

**Comment by MrPowerGamerBR** [comment]
I updated SparklyPaper to 1.20.6, but as always: I haven't tested it in production yet because my server is still running 1.20.2 (I'm planning to update it to 1.20.6 soon tho)
