### ISSUE TITLE
FAWE not fully compatible? //extinguish doesn't work

### ISSUE THREAD

**Issue by DaddyRobLIVE** [SparklyPower/SparklyPaper#19]
![image](https://github.com/SparklyPower/SparklyPaper/assets/109517972/433b90cd-e324-44cc-a666-ab191aba0bd2)

Are you guys using a different plugin?
Please suggest a plugin that works, ty!

**Comment by MrPowerGamerBR** [comment]
Share the FAWE stacktrace, SparklyPaper does have some async world read checks, but I *think* I can remove them, I need to double check if Folia has the same checks (there was a time that I added a lot of checks that Folia didn't have just to be sure I wasn't have any concurrency issues)

We use vanilla WorldEdit on SparklyPower

**Comment by DaddyRobLIVE** [comment]
Oh, nevermind. It's working now. Looks like it's FAWE's fault. They got it fixed on the latest update.
