### ISSUE TITLE
Inventory Error?

### ISSUE THREAD

**Issue by DaddyRobLIVE** [SparklyPower/SparklyPaper#22]
![image](https://github.com/user-attachments/assets/7864acaf-b122-4efd-affa-36d2487782d8)

This keeps showing up on my console and Idk what's causing it

**Comment by MrPowerGamerBR** [comment]
It is not a error, this is just a log that I have added to debug issues when respawning players.

**Comment by DaddyRobLIVE** [comment]
> It is not a error, this is just a log that I have added to debug issues when respawning players.

I see, is it possible to turn it off?

**Comment by MrPowerGamerBR** [comment]
> I see, is it possible to turn it off?

Not yet

**Comment by DaddyRobLIVE** [comment]
Okay, I'll just wait til it's possible.
