### ISSUE TITLE
Worldedit not working properly

### ISSUE THREAD

**Issue by DaddyRobLIVE** [SparklyPower/SparklyPaper#23]
The worldedit plugin is not working properly. Here is what commonly happens:

- //set a large area sometimes causes an unprocessed chunk
- //paste a large build sometimes causes an unprocessed chunk
- //copy -e and //paste -e sometimes doesn't keep the entities
- //up doesn't work properly
- //ascend doesn't work properly

**Comment by MrPowerGamerBR** [comment]
We use WorldEdit on SparklyPower without any problems, I don't think this is a SparklyPaper issue tbh

The only similar thing that I have encountered is that when editing a large area the client has "unprocessed chunks", but that's only visual and reloading the chunk to the client (relogging, changing worlds, etc) fixes the issue.

**Comment by DaddyRobLIVE** [comment]
> We use WorldEdit on SparklyPower without any problems, I don't think this is a SparklyPaper issue tbh
> 
> The only similar thing that I have encountered is that when editing a large area the client has "unprocessed chunks", but that's only visual and reloading the chunk to the client (relogging, changing worlds, etc) fixes the issue.

Is that so? Are you also using coreprotect or you're using something else?

**Comment by MrPowerGamerBR** [comment]
> Are you also using coreprotect or you're using something else?

I'm using CoreProtect

**Comment by DaddyRobLIVE** [comment]
> > Are you also using coreprotect or you're using something else?
> 
> I'm using CoreProtect

Yeah, there's really lot of broken chunks during the paste on my server.
