### ISSUE TITLE
World loading/generating/unloading/deletion lag issue

### ISSUE THREAD

**Issue by DaddyRobLIVE** [SparklyPower/SparklyPaper#25]
I recently installed this plugin https://www.spigotmc.org/resources/rentit-worlds-rent-your-own-player-worlds.108855/
- It creates a private world for players and I noticed that this fork is not handling world generation well.
It drastically lags the server and could sometimes cause it to crash.

Can this be fixed or is there any reason it behaves like that?

**Comment by MrPowerGamerBR** [comment]
Have you tested it in vanilla Paper? Because I'm pretty sure that SparklyPaper does not interfere with anything world load/unload related, the only thing that could be lagging is that every new world creates a new thread for it. You need to share the stacktrace of the crash.

**Comment by DaddyRobLIVE** [comment]
Oh I see, I think it's because of creating new thread when a world is added. Is there any way to reduce the lag for that?
