### ISSUE TITLE
Cannot retrieve chunk asynchronously

### ISSUE THREAD

**Issue by DaddyRobLIVE** [SparklyPower/SparklyPaper#28]
LOG: https://mclo.gs/PFGjX5M
PLUGIN: https://www.spigotmc.org/resources/rentit-worlds-rent-your-own-player-worlds.108855/

**Comment by MrPowerGamerBR** [comment]
[Folia has the same check](https://github.com/PaperMC/Folia/blob/d79708296e75ee4f26e78c2925f6e7d4217d0575/patches/server/0003-Threaded-Regions.patch#L22111), however I think that check can be removed because the server is able to load chunks on a thread that is not the main thread.

**Comment by DaddyRobLIVE** [comment]
Nevermind, the dev of the plugin is fixing it already.
