### ISSUE TITLE
Please add FAWE Support

### ISSUE THREAD

**Issue by DaddyRobLIVE** [SparklyPower/SparklyPaper#30]
I've stuck with Worldedit for quite some time now as it's the only working option but there are many performance issues.

I noticed that these commands are not working well when using WE
- /asc
- /desc

The server also lags a lot and even crashes when pasting huge builds with WE. FAWE on the other hand is a lot faster and more optimized. Please make it compatible with this fork.

**Comment by MrPowerGamerBR** [comment]
Send the full FAWE console stacktrace for any FAWE command that is not working

**Comment by DaddyRobLIVE** [comment]
Thank you! I'll forward the data later just finishing work.

**Comment by MrPowerGamerBR** [comment]
Just a FYI: I tried running FastAsyncWorldEdit on a test server and I wasn't able to reproduce any of the FAWE issues, here's what I tried:

* `//ascend` and `//descend`
* `//extinguish` (that you reported in another issue that it wasn't working but it was actually FAWE's issue #19)
* Copying builds
* Pasting builds
* Setting a very large area

And none of these triggered any errors

**Comment by DaddyRobLIVE** [comment]
> Just a FYI: I tried running FastAsyncWorldEdit on a test server and I wasn't able to reproduce any of the FAWE issues, here's what I tried:
> 
> * `//ascend` and `//descend`
> * `//extinguish` (that you reported in another issue that it wasn't working but it was actually FAWE's issue [FAWE not fully compatible? //extinguish doesn't work #19](https://github.com/SparklyPower/SparklyPaper/issues/19))
> * Copying builds
> * Pasting builds
> * Setting a very large area
> 
> And none of these triggered any errors

For the //extinguish I actually reported it to them and they said they won't add support
