### ISSUE TITLE
Something wrong with the upstreams?

### ISSUE THREAD

**Issue by DaddyRobLIVE** [SparklyPower/SparklyPaper#35]
![image](https://github.com/user-attachments/assets/81aac8fe-d3fc-4afa-a31b-d079d28bb73f)

Please check, I think there's an issue with your automatic upstreams.

**Comment by DaddyRobLIVE** [comment]
![image](https://github.com/user-attachments/assets/00deb637-ce2b-477d-a071-e8e8c04d0eb9)

Please fix the upstreams :(

They are broken!

**Comment by MrPowerGamerBR** [comment]
I haven't fixed them yet because I haven't had time to do things on my Minecraft server

**Comment by DaddyRobLIVE** [comment]
I see, hope you'll have some time soon :(
