### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by HanielCota** [SparklyPower/SparklyPaper#4]
I simply downloaded the jar and put it on the server and started it (clean install), and then these errors came up.

![image](https://github.com/SparklyPower/SparklyPaper/assets/117860225/65cc3803-3151-4d43-8ab8-21a8a8e7823b)
![image](https://github.com/SparklyPower/SparklyPaper/assets/117860225/9da0a8d3-9065-4c02-a27e-7d3636022efe)

**Comment by MrPowerGamerBR** [comment]
Disable Aikar timings in `paper-global.yml`, I haven't tested with timings because tbh, nowadays, I prefer using Spark because Spark doesn't incurr a performance penalty on the server and you can dig deep with Spark since you are profiling the server code and can see each method CPU %.

**Comment by MrPowerGamerBR** [comment]
Now SparklyPaper refuses to enable Timings if the Parallel World Ticking patch was applied when building the server :3

**Comment by HanielCota** [comment]
Amazing, congratulations on your work.
