### ISSUE TITLE
Upstream issue

### ISSUE THREAD

**Issue by DaddyRobLIVE** [SparklyPower/SparklyPaper#42]
![image](https://github.com/user-attachments/assets/76870a34-a03c-45e3-8ed5-038c09ab443d)

**Comment by MrPowerGamerBR** [comment]
Fixed, the issue was that the script always pulls the latest commit hash from Paper `master` branch, and because Paper's `master` branch is now using another version (1.12.3) the patches were conflicting due to changes

**Comment by DaddyRobLIVE** [comment]
Thank you!
